# [Choice] Alpine version: 3.12, 3.11, 3.10
ARG VARIANT=12.18.3
FROM mhart/alpine-node:${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>

RUN apk add bash
RUN apk add git
